stages:
  - build
  - package
  - deploy

java-build: 
  stage: build
  language: java
  jdk:
    - oraclejdk8
  env:
    global:
    - CODECOV_TOKEN=988bb1ee-29f3-46af-8b7d-7b6d08ee6256
  branches:
    only:
    - master
    - develop
  script:
    - cd knuca-schedule \ && ./gradlew build
    - bash <(curl -s https://codecov.io/bash)
    - ./gradlew dockerfile

docker-build:
  stage: package
  sudo: required
  services:
    - docker
  script:
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  - docker build -t knuca-image docker/.; docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
  - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:latest
  - docker push $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_HUB_USERNAME/knuca-platform:latest; ./gradlew jacocoTestReport

gcp-deploy:
  stage: deploy
  script: 
    - ls
  
