language: java
  jdk:
    - oraclejdk8
sudo: required
  services:
      - docker

stages:
  - "Build"
  - "Package"
  - "Deploy"

jobs:
  include:
    - stage: "Build"
      name: "Java build"
      script: cd knuca-schedule \ && ./gradlew build
    - script: bash <(curl -s https://codecov.io/bash)
      name: "Codecov publish"
    - script: ./gradlew dockerfile
      name: "Dockerfile generate"

    - stage: "Package"
      before_script: docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
      name: "Docker build"
      script: - docker build -t knuca-image docker/.; docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
    - script:
      - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:latest
      - docker push $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_HUB_USERNAME/knuca-platform:latest; ./gradlew jacocoTestReport
      name: "Docker publish"

    - stage: "Deploy"
      script: ls
