language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
stages:
  - Build
  - Package
  - Deploy
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.gradle"
before_script:
  - cd knuca-schedule
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
jobs:
  include:
  - 
    stage: Build
    name: Build-Package
    script:
    - "./gradlew build"
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
    - "./gradlew dockerfile"
    - docker build -t knuca-image docker/.
    - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
    - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:latest
    - docker push $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_HUB_USERNAME/knuca-platform:latest;
  - 
    stage: Deploy
    name: GCP Deploy
    script: ls
before_install:
  - openssl aes-256-cbc -K $encrypted_77ea7f21850c_key -iv $encrypted_77ea7f21850c_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - wget -qO-  https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-209.0.0-linux-x86_64.tar.gz | tar xvz && \ 
    ./google-cloud-sdk/install.sh -q
  - tar -xzf credentials.tar.gz
  - mkdir -p lib
  - gcloud auth activate-service-account --key-file client-secret.json
