language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
stages:
  - Build
  - Deploy
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.gradle"
before_script:
  - cd knuca-schedule
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  
jobs:
  include:
  - 
    stage: Build
    name: Build-Package
    script:
    - "./gradlew build"
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
    - "./gradlew dockerfile"
    - docker build -t knuca-image docker/.
    - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
    - docker tag knuca-image $DOCKER_HUB_USERNAME/knuca-platform:latest
    - docker push $DOCKER_HUB_USERNAME/knuca-platform:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_HUB_USERNAME/knuca-platform:latest
