server:
  port: 8080
  jetty:
    threadPool:
      maxThreads: 100
      minThreads: 10
      idleTimeout: 30000
spring:
  http:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
  profiles.active: upload
  datasource:
    url: jdbc:mysql://localhost:3306/knuca?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
logging:
  file: ../logs/knuca-rest.log
api:
  swagger:
    path: "/api/docs"
    basePackage: "com.theopus"
