server:
  port: 8090
spring:
  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  profiles:
    active:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
logging:
  file: ../logs/knuca-upload.log

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/knuca-upload?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: dev
  profiles.include: nosecure
  datasource.initialization-mode: always
  jpa.hibernate.ddl-auto: update
  h2.console.enabled: true
  h2.console.path: /h2
  datasource.platform: h2
  datasource.schema: classpath:dumps/dump-29-03-2018.sql
---
spring:
  profiles: nosecure
security.ignored: /**
spring.security.enabled: false
management.security.enabled: false
security.basic.enabled: false
